/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,name varchar(255),date_of_birth date,escape_attempts integer,neutered boolean,weight_kg decimal);

ALTER TABLE animals
ADD 
COLUMN species VARCHAR(255);

-- Create the 'owners' table
CREATE TABLE owners (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255),
    age INTEGER
);

-- Create the 'species' table
CREATE TABLE species (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255)
);

-- Modify the 'animals' table
ALTER TABLE animals
    ALTER TABLE animals ADD COLUMN id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    DROP COLUMN species,
    ADD COLUMN species_id INTEGER REFERENCES species(id),
    ADD COLUMN owner_id INTEGER REFERENCES owners(id);
